# Production configuration
version: '3.8'

services:
  driftdetect:
    restart: unless-stopped
    build:
      target: runtime
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "driftdetect", "list", "repos"]
      interval: 30s
      timeout: 3s
      retries: 3
    user: driftdetect
    volumes:
      - driftdetect-config:/home/driftdetect/.driftdetect
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  driftdetect-config: 