# Base configuration shared across all environments

services:
  driftdetect:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.driftdetect:/home/driftdetect/.driftdetect
    environment:
      - TZ=UTC