# Development configuration
version: '3.8'

services:
  driftdetect:
    build:
      target: builder
    volumes:
      - .:/app
      - go-cache:/go/pkg/mod
    command: ["go", "run", "main.go"]
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GO111MODULE=on
    ports:
      - "8080:8080"

volumes:
  go-cache: 