# Debug configuration with delve debugger
version: '3.8'

services:
  driftdetect:
    build:
      target: builder
    volumes:
      - .:/app
      - go-cache:/go/pkg/mod
    command: ["dlv", "debug", "--headless", "--listen=:2345", "--api-version=2", "--accept-multiclient"]
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    ports:
      - "2345:2345"
      - "8080:8080"
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GO111MODULE=on

volumes:
  go-cache: 