apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
- configmap.yaml
- network-policy.yaml

commonLabels:
  app: driftdetect

namespace: driftdetect 