apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: driftdetect-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 