---
repos:
  - name: examples
    path: repos/examples
    git:
      url: https://github.com/marc-israel/DriftDetect
  - name: forgearmory
    path: repos/forgearmory
    git:
      url: https://github.com/facebookincubator/forgearmory
